### ISSUE TITLE
Throw BadImageFormatException when call draw graph function

### ISSUE THREAD

**Issue by TihonchukArtyom89** [PolarGoose/GraphvizWpf#1]
Hi! I am start to use GraphvizWpf and it look very potential. Launch test project from this repository. But when i rewrite code from test project it not working. Copy the dll files from Grapviz archive  bin folder  to project bin/Debug folder. Code from my project:

        private void Window_Initialized(object sender, EventArgs e)
        {
            path = path.Replace($"\\bin\\Debug", "");
            string[] files = Directory.GetFiles(path + "DotGraphs");
            dotFileComboBox.ItemsSource = files.Select(System.IO.Path.GetFileName);
            dotFileComboBox.SelectedIndex = 0;
            dotFileComboBox.SelectedItem = files[dotFileComboBox.SelectedIndex];
            dotFileComboBox.SelectionChanged += dotFileComboBox_SelectionChanged;
            DotLayoutEngine[] dotLayoutEngines = new DotLayoutEngine[]
            {
                DotLayoutEngine.dot,
                DotLayoutEngine.neato,
                DotLayoutEngine.circo,
                DotLayoutEngine.fdp,
                DotLayoutEngine.osage,
                DotLayoutEngine.twopi
            };
            layoutEngineComboBox.ItemsSource = dotLayoutEngines;
            layoutEngineComboBox.SelectedIndex = 0;
            layoutEngineComboBox.SelectedItem = dotLayoutEngines[layoutEngineComboBox.SelectedIndex];
            layoutEngineComboBox.SelectionChanged += layoutEngineComboBox_SelectionChanged;
            DrawGraph();
        }
        public void DrawGraph()
        {
            string dot = File.ReadAllText(path + $"DotGraphs/{dotFileComboBox.SelectedItem}");
            graphvizCanvas.DrawGraph(dot, (DotLayoutEngine)layoutEngineComboBox.SelectedItem);
            foreach (var child in graphvizCanvas.Children.OfType<FrameworkElement>().Where(e => e.Tag is DotVertex))
            {
                var vertex = (DotVertex)child.Tag;
                var tooltip = new ToolTip { Content = $"Node: {vertex.Name}" };
            }
        }
        private void dotFileComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            DrawGraph();
        }
        private void layoutEngineComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            DrawGraph();
        }

This line of code `graphvizCanvas.DrawGraph(dot, (DotLayoutEngine)layoutEngineComboBox.SelectedItem);` 
 is throw System.BadImageFormatException.

**Comment by PolarGoose** [comment]
Hello Artyom,

Thank you for the bug report.
Could you please attach your whole solution folder?
I think there is something wrong with the dependency on the [GraphvizWpf](https://github.com/PolarGoose/GraphvizWpf) library.

**Comment by TihonchukArtyom89** [comment]
Thank for your answer. I manually copy the dll files and configure6 file to folder bin/Debug in project.
[Uploading TestGraphVizWpfApplication.zip…]()

**Comment by TihonchukArtyom89** [comment]
Thank for your answer. I manually copy the dll files and configure6 file to folder bin/Debug in project.
[Uploading TestGraphVizWpfApplication.zip…]()

**Comment by TihonchukArtyom89** [comment]
Thank you for your answer. Sure. 
[TestGraphVizWpfApplication.zip](https://github.com/user-attachments/files/18071738/TestGraphVizWpfApplication.zip)

**Comment by PolarGoose** [comment]
I have found the problem:
You need to set the build architecture to `x64`:
![image](https://github.com/user-attachments/assets/fcbd5583-8f83-444c-8f53-745b60ebe932)
Then you need to change this line so that it uses the correct path:
`path = path.Replace($"\\bin\\x64\\Debug", "");`

Then it works :)

> Логика взаимодействия для MainWindow.xaml

I guess your Visual Studio language is selected to Russian :) Better use the English language, because the translation is quite bad and you will have problems if you want to Google something.

Also, what is the reason that you are trying to use `GraphvizWpf` library? I'm just curious because there might be better options to solve your problem.

**Comment by TihonchukArtyom89** [comment]
Thank you very much. It helps me a lot. I try GraphvizWpf because my project on WPF and looks like in Graphviz there is an option to draw node with specified coordinates. It need to implement algorithm of laying to attributed hierarchical graph with ports (and in Graphviz there are these possibilities too ^-^)

**Comment by PolarGoose** [comment]
Great.
`GraphvizWpf` is needed if you want to have an interactive graph. If you just need to visualise DOT graph representation, then you can just use Graphviz directly to generate SVG or PNG image and show it in your WPF. You don't need any library for that. It is also much easier code-wise.

**Comment by TihonchukArtyom89** [comment]
Yes interactive graph with context menu for each node, edge. For porject it will be great)
