### ISSUE TITLE
Get error when try to render svg

### ISSUE THREAD

**Issue by TihonchukArtyom89** [PolarGoose/GraphvizWpf#2]
Hi! I am rework test project from this repo to using svg and get cs 0122  'DotGraphDescriptionProcessor' is inaccessible due to its protection level. Code with error on this link 45.5 Mb [https://dropmefiles.com/OxY77](url)

**Comment by PolarGoose** [comment]
This method is inernal. The test project uses it to generate an SVG image.
It is not a part of the `GraphvizWpf` library. Thus you can't use it.

Do you need to generate SVG? You can just remove this functionality from your program.

**Comment by TihonchukArtyom89** [comment]
Yes, I need this because the DrawGraph function genereate null exception even though all parameters passed to this function are fine. Unfortunately, I cannot add a project with such an error because I am participating in the NDA.

**Comment by TihonchukArtyom89** [comment]
Yes, I need this because the DrawGraph function generate argument exception "Unable to read the given graph description. aglasterr:" even though all parameters passed to this function are fine at first sight. Unfortunately, I cannot add a project with such an error because I am participating in the NDA.

**Comment by PolarGoose** [comment]
Can you share the graphviz dot input that you are trying to draw?

**Comment by TihonchukArtyom89** [comment]
Sure. Here is it. [graph.zip](https://github.com/user-attachments/files/18145081/graph.zip)

**Comment by TihonchukArtyom89** [comment]
I find what is problem Draw function throws an exception when in graph string not have an edges. Thank you for your desire to help)
